version: '3.4'

services:
  nodejs:
    env_file: 'app/.env'
    environment:
      NODE_ENV: 'development'
    build:
      context: .
    volumes:
      - ./app:/srv/app
    ports:
      - "3000:3000"